apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sudipto2104/platform-config-repo.git
    targetRevision: main
    path: charts/demo-platform-chart
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
